export const categories = [
  {
    id: "hepsi",
    name: "Tüm İlanlar",
    listingCount: 50000,
  },
  {
    id: "emlak",
    name: "Emlak",
    listingCount: 10000,
  },
  {
    id: "arsa",
    name: "Arsa",
    listingCount: 10000,
  },
  {
    id: "konut",
    name: "Konut",
    listingCount: 10000,
  },
  {
    id: "turistik_tesis",
    name: "Turistik Tesis",
    listingCount: 10000,
  },
  {
    id: "araç",
    name: "Araç",
    listingCount: 9996,
  },
  {
    id: "otomobil",
    name: "Otomobil",
    listingCount: 1,
  },
  {
    id: "motosiklet",
    name: "Motosiklet",
    listingCount: 1,
  },
  {
    id: "karavan",
    name: "Karavan",
    listingCount: 1,
  },
  {
    id: "tır",
    name: "Tır",
    listingCount: 1,
  },
];

export const listings = [
  {
    id: 1,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 2,
    city: "İstanbul",
    year: 2025,
    title: "Peugeot",
    price: "120.000 TL",
  },
  {
    id: 3,
    city: "Konya",
    year: 2018,
    title: "Leon",
    price: "15.120.000 TL",
  },
  {
    id: 4,
    city: "Çankırı",
    year: 2004,
    title: "Ferrari",
    price: "1.950.000 TL",
  },
  {
    id: 5,
    city: "Balıkesir",
    year: 2003,
    title: "Ferrari",
    price: "1.730.000 TL",
  },
  {
    id: 6,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 7,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 8,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 9,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 10,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 11,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 12,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 13,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 14,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
  {
    id: 15,
    city: "Ankara",
    year: 2025,
    title: "Audi A4",
    price: "110.000 TL",
  },
];
